In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [4]:
data=pd.read_csv(r'/Users/rahulpoojith/Desktop/Bank Customer Churn prediction using Deep Learning/Data/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [6]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [7]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [8]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [11]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/opt/anaconda3/envs/annvenv/lib/python3.9/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [18]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 978us/step - loss: 101213.2891 - mae: 101213.2891 - val_loss: 98459.1172 - val_mae: 98459.1172
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - loss: 99701.7266 - mae: 99701.7266 - val_loss: 96537.2422 - val_mae: 96537.2422
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - loss: 96568.2422 - mae: 96568.2422 - val_loss: 91690.3125 - val_mae: 91690.3125
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - loss: 91207.4062 - mae: 91207.4062 - val_loss: 83936.7344 - val_mae: 83936.7344
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 83064.0156 - mae: 83064.0156 - val_loss: 74333.8594 - val_mae: 74333.8594
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 73487.5000 - mae: 73487.5000 - val_loss: 64993.3125 - val_mae: 64993.3125
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - loss: 63604.2734 - mae: 63604.2734 - val_loss: 57731.5703 - val_mae: 57731.5703
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - loss: 56817.5039 - mae: 56817.5039 - val_loss: 53491.1328 - val_mae: 53491.1328
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - loss: 53428.1133 - mae: 53428.1133 - val_loss: 51558.3008 - val_mae: 51558.3008
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 51516.6523 - mae: 51516.6523 - val_loss: 50910.9453 - val_mae: 50910.9453
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 50912.9336 - mae: 50912.9336 - val_loss: 50731.9297 - val_mae: 50731.9297
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 51293.3867 - mae: 51293.3867 - val_loss: 50685.7422 - val_mae: 50685.7422
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 49956.3203 - mae: 49956.3203 - val_loss: 50654.2227 - val_mae: 50654.2227
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 50754.7305 - mae: 50754.7305 - val_loss: 50620.0469 - val_mae: 50620.0469
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 50397.2852 - mae: 50397.2852 - val_loss: 50591.0742 - val_mae: 50591.0742
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 50563.5195 - mae: 50563.5195 - val_loss: 50573.4883 - val_mae: 50573.4883
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - loss: 49426.6016 - mae: 49426.6016 - val_loss: 50531.9531 - val_mae: 50531.9531
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 49920.5117 - mae: 49920.5117 - val_loss: 50503.4062 - val_mae: 50503.4062
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 50155.4102 - mae: 50155.4102 - val_loss: 50488.0781 - val_mae: 50488.0781
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 49749.4570 - mae: 49749.4570 - val_loss: 50472.0898 - val_mae: 50472.0898
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 49723.9766 - mae: 49723.9766 - val_loss: 50459.5898 - val_mae: 50459.5898
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 49560.4258 - mae: 49560.4258 - val_loss: 50443.3359 - val_mae: 50443.3359
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 49956.6953 - mae: 49956.6953 - val_loss: 50425.5938 - val_mae: 50425.5938
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 49511.2539 - mae: 49511.2539 - val_loss: 50417.1953 - val_mae: 50417.1953
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 49745.9922 - mae: 49745.9922 - val_loss: 50405.3086 - val_mae: 50405.3086
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 49708.3633 - mae: 49708.3633 - val_loss: 50385.4062 - val_mae: 50385.4062
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49099.1445 - mae: 49099.1445 - val_loss: 50383.1836 - val_mae: 50383.1836
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 49142.6836 - mae: 49142.6836 - val_loss: 50372.7109 - val_mae: 50372.7109
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - loss: 50141.0859 - mae: 50141.0859 - val_loss: 50364.6367 - val_mae: 50364.6367
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 49832.0859 - mae: 49832.0859 - val_loss: 50345.2969 - val_mae: 50345.2969
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - loss: 49760.8906 - mae: 49760.8906 - val_loss: 50342.7773 - val_mae: 50342.7773
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 50192.6445 - mae: 50192.6445 - val_loss: 50342.1992 - val_mae: 50342.1992
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - loss: 49836.3711 - mae: 49836.3711 - val_loss: 50338.7891 - val_mae: 50338.7891
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 49848.0938 - mae: 49848.0938 - val_loss: 50316.9805 - val_mae: 50316.9805
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 49580.0312 - mae: 49580.0312 - val_loss: 50329.3828 - val_mae: 50329.3828
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 49715.8516 - mae: 49715.8516 - val_loss: 50325.0352 - val_mae: 50325.0352
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 49520.7383 - mae: 49520.7383 - val_loss: 50327.7031 - val_mae: 50327.7031
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 49239.1875 - mae: 49239.1875 - val_loss: 50326.0039 - val_mae: 50326.0039
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 49728.7070 - mae: 49728.7070 - val_loss: 50327.1914 - val_mae: 50327.1914
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - loss: 49813.0234 - mae: 49813.0234 - val_loss: 50322.7539 - val_mae: 50322.7539
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49549.3008 - mae: 49549.3008 - val_loss: 50303.6758 - val_mae: 50303.6758
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 49434.2773 - mae: 49434.2773 - val_loss: 50309.3047 - val_mae: 50309.3047
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - loss: 49221.7109 - mae: 49221.7109 - val_loss: 50318.3086 - val_mae: 50318.3086
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49662.9961 - mae: 49662.9961 - val_loss: 50315.6250 - val_mae: 50315.6250
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - loss: 50475.4258 - mae: 50475.4258 - val_loss: 50318.7539 - val_mae: 50318.7539
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - loss: 49213.1836 - mae: 49213.1836 - val_loss: 50310.6953 - val_mae: 50310.6953
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 49235.1406 - mae: 49235.1406 - val_loss: 50298.2188 - val_mae: 50298.2188
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 49476.7422 - mae: 49476.7422 - val_loss: 50295.7344 - val_mae: 50295.7344
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - loss: 48836.6484 - mae: 48836.6484 - val_loss: 50299.9883 - val_mae: 50299.9883
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49344.9766 - mae: 49344.9766 - val_loss: 50307.9609 - val_mae: 50307.9609
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 49615.7695 - mae: 49615.7695 - val_loss: 50313.0977 - val_mae: 50313.0977
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 49442.2812 - mae: 49442.2812 - val_loss: 50309.1758 - val_mae: 50309.1758
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 49867.1445 - mae: 49867.1445 - val_loss: 50307.2422 - val_mae: 50307.2422
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - loss: 49671.6523 - mae: 49671.6523 - val_loss: 50311.1289 - val_mae: 50311.1289
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - loss: 49246.4609 - mae: 49246.4609 - val_loss: 50313.1055 - val_mae: 50313.1055
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - loss: 49375.9922 - mae: 49375.9922 - val_loss: 50315.6367 - val_mae: 50315.6367
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 49889.4141 - mae: 49889.4141 - val_loss: 50311.3867 - val_mae: 50311.3867
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - loss: 48897.5078 - mae: 48897.5078 - val_loss: 50311.9453 - val_mae: 50311.9453

In [19]:
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit

In [21]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - loss: 51119.7578 - mae: 51119.7578
Test MAE : 50295.734375

In [22]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.